import type { MenuItem } from './types'

// Placeholder data in the shape of backend `menu_rows()`, trimmed from
// backend/seed.py. Swap for a real fetch in api.ts once the backend serves it.
export const MOCK_MENU: MenuItem[] = [
  {
    id: 'fall_parfait',
    name: 'Fall Parfait',
    bakery: 'grandmas_bakeria',
    category: 'dessert',
    description: 'Whipped cream, spiced pumpkin, maple granola, candied pecans.',
    flavor: {
      sweet_savoury: 0.55,
      bitterness: 0.08,
      fruitiness: 0.45,
      categories: ['caramel', 'fruit', 'nut', 'spice'],
    },
    price: 8.5,
    portion_size_g: 340,
    allergens: ['dairy', 'gluten', 'tree_nut'],
    daypart_weights: { early_morning: 0.1, morning: 0.4, lunch: 0.7, afternoon: 1.0, evening: 0.8 },
  },
  {
    id: 'morning_bun',
    name: 'Morning Bun',
    bakery: 'grandmas_bakeria',
    category: 'pastry',
    description: 'Laminated dough rolled in cinnamon sugar.',
    flavor: { sweet_savoury: 0.6, bitterness: 0.1, fruitiness: 0.05, categories: ['caramel', 'spice'] },
    price: 4.25,
    portion_size_g: 110,
    allergens: ['dairy', 'egg', 'gluten'],
    daypart_weights: { early_morning: 1.0, morning: 0.95, lunch: 0.4, afternoon: 0.3, evening: 0.1 },
  },
  {
    id: 'sourdough_loaf',
    name: 'Sourdough Loaf',
    bakery: 'grandmas_bakeria',
    category: 'bread',
    description: 'Three-day starter, baked each morning.',
    flavor: { sweet_savoury: -0.4, bitterness: 0.2, fruitiness: 0.05, categories: [] },
    price: 7.0,
    portion_size_g: 800,
    allergens: ['gluten'],
    daypart_weights: { early_morning: 0.8, morning: 0.9, lunch: 0.6, afternoon: 0.5, evening: 0.3 },
  },
  {
    id: 'lemon_tart',
    name: 'Lemon Tart',
    bakery: 'grandmas_bakeria',
    category: 'dessert',
    description: 'Shortcrust, lemon curd, torched meringue.',
    flavor: { sweet_savoury: 0.5, bitterness: 0.15, fruitiness: 0.85, categories: ['citrus', 'fruit'] },
    price: 5.75,
    portion_size_g: 140,
    allergens: ['dairy', 'egg', 'gluten'],
    daypart_weights: { early_morning: 0.1, morning: 0.3, lunch: 0.7, afternoon: 0.9, evening: 0.8 },
  },
  {
    id: 'hot_chocolate',
    name: 'Hot Chocolate',
    bakery: 'grandmas_bakeria',
    category: 'drink',
    description: 'Dark chocolate melted into whole milk.',
    flavor: { sweet_savoury: 0.7, bitterness: 0.4, fruitiness: 0.0, categories: ['chocolate'] },
    price: 4.5,
    portion_size_g: 350,
    allergens: ['dairy'],
    daypart_weights: { early_morning: 0.8, morning: 0.8, lunch: 0.5, afternoon: 0.7, evening: 0.9 },
  },
  {
    id: 'gruyere_croissant',
    name: 'Ham & Gruyère Croissant',
    bakery: 'grandmas_bakeria',
    category: 'sandwich',
    description: "Yesterday's croissants, split and baked with béchamel.",
    flavor: { sweet_savoury: -0.6, bitterness: 0.1, fruitiness: 0.0, categories: ['cheese', 'savoury'] },
    price: 7.25,
    portion_size_g: 160,
    allergens: ['dairy', 'egg', 'gluten'],
    daypart_weights: { early_morning: 0.4, morning: 0.7, lunch: 1.0, afternoon: 0.5, evening: 0.2 },
  },
  {
    id: 'autumn_parfait',
    name: 'Autumn Parfait',
    bakery: 'the_bakery',
    category: 'dessert',
    description: 'Pumpkin spice parfait with granola. Suspiciously familiar.',
    flavor: {
      sweet_savoury: 0.65,
      bitterness: 0.06,
      fruitiness: 0.38,
      categories: ['caramel', 'fruit', 'nut', 'spice'],
    },
    price: 6.95,
    portion_size_g: 290,
    allergens: ['dairy', 'gluten', 'tree_nut'],
    daypart_weights: { early_morning: 0.2, morning: 0.5, lunch: 0.8, afternoon: 1.0, evening: 0.7 },
  },
  {
    id: 'cinnamon_swirl',
    name: 'Cinnamon Swirl',
    bakery: 'the_bakery',
    category: 'pastry',
    description: 'Frosted, shelf-stable, available every day of the year.',
    flavor: { sweet_savoury: 0.85, bitterness: 0.05, fruitiness: 0.0, categories: ['caramel', 'spice'] },
    price: 3.95,
    portion_size_g: 130,
    allergens: ['dairy', 'gluten', 'soy'],
    daypart_weights: { early_morning: 1.0, morning: 1.0, lunch: 0.6, afternoon: 0.5, evening: 0.3 },
  },
  {
    id: 'multigrain_loaf',
    name: 'Multigrain Loaf',
    bakery: 'the_bakery',
    category: 'bread',
    description: 'Par-baked off-site, finished in store.',
    flavor: { sweet_savoury: -0.25, bitterness: 0.25, fruitiness: 0.05, categories: [] },
    price: 5.5,
    portion_size_g: 700,
    allergens: ['gluten', 'sesame', 'soy'],
    daypart_weights: { early_morning: 0.7, morning: 0.8, lunch: 0.6, afternoon: 0.5, evening: 0.4 },
  },
  {
    id: 'lemon_square',
    name: 'Lemon Square',
    bakery: 'the_bakery',
    category: 'dessert',
    description: 'Dusted with powdered sugar.',
    flavor: { sweet_savoury: 0.75, bitterness: 0.05, fruitiness: 0.7, categories: ['citrus', 'fruit'] },
    price: 3.75,
    portion_size_g: 95,
    allergens: ['dairy', 'egg', 'gluten', 'soy'],
    daypart_weights: { early_morning: 0.2, morning: 0.4, lunch: 0.8, afternoon: 0.9, evening: 0.6 },
  },
  {
    id: 'mocha_latte',
    name: 'Mocha Latte',
    bakery: 'the_bakery',
    category: 'drink',
    description: 'Large by default.',
    flavor: { sweet_savoury: 0.6, bitterness: 0.55, fruitiness: 0.0, categories: ['chocolate', 'coffee'] },
    price: 5.25,
    portion_size_g: 470,
    allergens: ['dairy'],
    daypart_weights: { early_morning: 1.0, morning: 1.0, lunch: 0.7, afternoon: 0.6, evening: 0.3 },
  },
  {
    id: 'turkey_club',
    name: 'Turkey Club',
    bakery: 'the_bakery',
    category: 'sandwich',
    description: 'Pre-wrapped, grab and go.',
    flavor: { sweet_savoury: -0.7, bitterness: 0.05, fruitiness: 0.05, categories: ['savoury'] },
    price: 9.5,
    portion_size_g: 320,
    allergens: ['egg', 'gluten', 'soy'],
    daypart_weights: { early_morning: 0.1, morning: 0.3, lunch: 1.0, afternoon: 0.6, evening: 0.4 },
  },
]
